name = "MarineSystemsSim"
uuid = "81223ba3-ea73-41df-8355-662df8ce4c82"
version = "0.1.0"
authors = ["Daniel Flataker"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DifferentialEquations = "7.17"
DocStringExtensions = "0.9"
Documenter = "1"
DocumenterTools = "0.1.21"
ForwardDiff = "1"
OrdinaryDiffEq = "6"
StaticArrays = "1"
Unitful = "1"
julia = "1.10"

[extras]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OrdinaryDiffEq", "Test", "DifferentialEquations", "ForwardDiff"]
